name: Deploy bbh2 to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying bbh2
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate gcloud CLI
      - name: Authenticate gcloud CLI
        uses: google-github-actions/auth@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}

      # Set up Google Cloud SDK
      - name: Setting up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: bigbutthippo420v2

      - name: Building
        run: |
          gcloud builds submit \
            --tag gcr.io/bigbutthippo420v2/bigbutthippo420-2-0

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: bigbutthippo420-2-0
          image: gcr.io/bigbutthippo420v2/bigbutthippo420-2-0
          region: us-east1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
