name: Deploy bbh2 to cloud run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying bbh2
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container 
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: "git-actions@bigbutthippo420v2.iam.gserviceaccount.com"
          project_id: bigbutthippo420v2

      - name: Building ()
        run: |-
          gcloud builds submit \
            --tag gcr.io/bigbutthippo420v2/bigbutthippo420-2-0

      # Setup gcloud CLI
      - name: Deploy ()
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: bigbutthippo420-2-0
          image: gcr.io/bigbutthippo420v2/bigbutthippo420-2-0
          region: us-east1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: bigbutthippo420v2